List imageList = [
  {'img': 'assets/img/images/inspirational.jpeg'},
  {'img': 'assets/img/images/life.jpeg'},
  {'img': 'assets/img/images/motivational.jpeg'},
  {'img': 'assets/img/images/wisdom.jpg'},
  {'img': 'assets/img/images/love.jpeg'},
  {'img': 'assets/img/images/technology.jpg'},
  {'img': 'assets/img/images/creativity.jpg'},
  {'img': 'assets/img/images/courage.jpg'},
  {'img': 'assets/img/images/nature.jpeg'},
  {'img': 'assets/img/images/positive.jpeg'},
  {'img': 'assets/img/images/wisdom2.jpeg'},
  //perseverance
  {'img': 'assets/img/images/goal.jpeg'},
  {'img': 'assets/img/images/success.jpeg'},
  {'img': 'assets/img/images/friendship.jpeg'},
  {'img': 'assets/img/images/idea.jpeg'},
  {'img': 'assets/img/images/courage2.jpeg'},
  {'img': 'assets/img/images/hope.jpg'},
  {'img': 'assets/img/images/advanture.jpg'},
  {'img': 'assets/img/images/knowladge.jpeg'},
  {'img': 'assets/img/images/happy.jpeg'},
  {'img': 'assets/img/images/wisdom.jpg'},
  {'img': 'assets/img/images/love.jpeg'},
  {'img': 'assets/img/images/imagination.jpeg'},
  {'img': 'assets/img/images/optimsm.jpeg'},
  {'img': 'assets/img/images/goal.jpeg'},
  {'img': 'assets/img/images/leadership.jpeg'},
  {'img': 'assets/img/images/goal.jpeg'},
  {'img': 'assets/img/images/curiosity.jpg'},

];
List bgList=[
  {'bg': 'assets/img/background/bg1.jpeg'},
  {'bg': 'assets/img/background/bg2.jpeg'},
  {'bg': 'assets/img/background/bg3.jpg'},
  {'bg': 'assets/img/background/bg4.jpeg'},
  {'bg': 'assets/img/background/bg5.jpg'},
  {'bg': 'assets/img/background/bg6.jpeg'},
  {'bg': 'assets/img/background/bg7.jpg'},
  {'bg': 'assets/img/background/bg8.jpeg'},
  {'bg': 'assets/img/background/bg9.jpg'},
  {'bg': 'assets/img/background/bg10.jpeg'},
  {'bg': 'assets/img/images/inspirational.jpeg'},
  {'bg': 'assets/img/images/inspirational.jpeg'},
  {'bg': 'assets/img/images/inspirational.jpeg'},
];